apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-simple-deployment
  labels: 
    app: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: DOCKER_IMAGE
        ports:
        - containerPort: 8000
        
