apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-container
        image: docker:latest
        ports:
        - containerPort: 8000