apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple-container
        image: 594709136083.dkr.ecr.us-east-1.amazonaws.com/python/pythonfirst:latest
        ports:
        - containerPort: 8000
